/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as MatchesMatchNumRouteImport } from './routes/matches.$matchNum'
import { Route as DashboardChar123UserIdChar125RouteImport } from './routes/dashboard.{-$userId}'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchNumRoute = MatchesMatchNumRouteImport.update({
  id: '/matches/$matchNum',
  path: '/matches/$matchNum',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChar123UserIdChar125Route =
  DashboardChar123UserIdChar125RouteImport.update({
    id: '/dashboard/{-$userId}',
    path: '/dashboard/{-$userId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/rules': typeof RulesRoute
  '/dashboard/{-$userId}': typeof DashboardChar123UserIdChar125Route
  '/matches/$matchNum': typeof MatchesMatchNumRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/rules': typeof RulesRoute
  '/dashboard/{-$userId}': typeof DashboardChar123UserIdChar125Route
  '/matches/$matchNum': typeof MatchesMatchNumRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/rules': typeof RulesRoute
  '/dashboard/{-$userId}': typeof DashboardChar123UserIdChar125Route
  '/matches/$matchNum': typeof MatchesMatchNumRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/rules'
    | '/dashboard/{-$userId}'
    | '/matches/$matchNum'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/rules'
    | '/dashboard/{-$userId}'
    | '/matches/$matchNum'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/rules'
    | '/dashboard/{-$userId}'
    | '/matches/$matchNum'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RulesRoute: typeof RulesRoute
  DashboardChar123UserIdChar125Route: typeof DashboardChar123UserIdChar125Route
  MatchesMatchNumRoute: typeof MatchesMatchNumRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchNum': {
      id: '/matches/$matchNum'
      path: '/matches/$matchNum'
      fullPath: '/matches/$matchNum'
      preLoaderRoute: typeof MatchesMatchNumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/{-$userId}': {
      id: '/dashboard/{-$userId}'
      path: '/dashboard/{-$userId}'
      fullPath: '/dashboard/{-$userId}'
      preLoaderRoute: typeof DashboardChar123UserIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RulesRoute: RulesRoute,
  DashboardChar123UserIdChar125Route: DashboardChar123UserIdChar125Route,
  MatchesMatchNumRoute: MatchesMatchNumRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
